OOC-4405: Update landing page (part 2) content (CQC checkbox)
ukhsa-collaboration/digital-form-builder pull request #211
Opened 2024-07-10 15:29 UTC by masuk-kazi98

# Description

- Introduced checkbox option for CQC ID, so users can select it if care setting is not registered
- Rearranged question order
- New validation for checkbox and textfield
- Checkbox selection clears text field and vice versa
- Content updates
- Have had to add 'novalidate' to the form.html to override javascript validation messages that would appear on the field like the example below. This was overwriting the helpers.error message from being shown. Should not affect joi validation on other pages
![image](https://github.com/ukhsa-collaboration/digital-form-builder/assets/90158744/fde3c3e3-4bf2-43bb-9f05-a39c3c86f463)
- Have created TextFieldCustom (extension of TextField) component to cover this edge case of checkbox+textfield validation, as the custom helpers function would also handle all other text fields on the page. The custom text field ensures only a single text field is being handled by the component
- The error messages will behave weirdly though. When form is submitted with no values entered for any fields, only the normal text fields will show errors. Once they are filled, and cqc text+checkbox left empty, THEN the new error message will show. Not found a workaround for this unfortunately

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally ✅

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [ ] I have updated the architecture diagrams as per Contribute.md OR added an architectural decision record entry

2024-07-11 14:33 UTC, kathryn-dale requested changes

2024-07-11 14:33 UTC, kathryn-dale commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +  pattern = "^(1-\\d{1,9}|[a-zA-Z0-9]{3,7})$";
Can we not pass "pattern" into the component, rather than hardcoding the pattern that's only used for one specific question?

2024-07-11 14:33 UTC, kathryn-dale commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcTextValue = payload["S0Q3"].trim();
I don't think we should hard code specific questions into the components

2024-07-11 14:48 UTC, masuk-kazi98 commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcTextValue = payload["S0Q3"].trim();
i didn't want to, but couldn't think of how else to implement this. open to suggestions. we only use this component for the cqc field currently, hopefully no more of these text+checkbox questions

2024-07-11 14:57 UTC, kathryn-dale commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcTextValue = payload["S0Q3"].trim();
To be honest I wish I had a suggestion. @connoravo @emilyjevans any ideas?

2024-07-11 15:12 UTC, emilyjevans commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcTextValue = payload["S0Q3"].trim();
Could you add some sort of custom indicator into the `options` object in the json for the question eg.... 

```
          "name": "S0Q3",
          "options": { "required": true, "firstDependentValue": true },
```

```
if this.options.firstDependentValue == true { 
const firstDependentValue = payload[this.name].trim(); 
}
```

2024-07-12 07:03 UTC, kathryn-dale requested changes

2024-07-12 07:03 UTC, kathryn-dale commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcTextValue = payload[this.name].trim();
I would rename from `cqcTextValue` to something like `currentFieldValue` to again keep it generic

2024-07-12 07:03 UTC, kathryn-dale commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcCheckbox = payload[this.dependentField];
Again, would rename this to something like `dependentFieldValue`

2024-07-12 09:13 UTC, masuk-kazi98 commented on runner/src/server/plugins/engine/components/TextFieldCustom.ts
> +    const cqcTextValue = payload[this.name].trim();
yeah good spot, missed this

2024-07-12 09:26 UTC, kathryn-dale commented on runner/src/server/plugins/engine/components/helpers.ts
> +export function customCqcValidator() {
Could this function be more generic than just cqc? I.e. could it be used for all dependency validations? Just wondering if we could make this reusable in case in future we get any similar requirements

2024-07-12 09:37 UTC, masuk-kazi98 commented on runner/src/server/plugins/engine/components/helpers.ts
> +export function customCqcValidator() {
can update the name for now, contents of the validator can be updated in the future based on requirements

2024-07-12 10:00 UTC, kathryn-dale approved these changes

2024-07-15 09:01 UTC, merged